In [2]:
import pandas as pd

In [9]:
pd.DataFrame({'Name':['Saurav','Rhit','Yashu','Raja','Gaurav','Sachin'],'Marks':[22,33,44,55,85,95]})

Name  Marks
0  Saurav     22
1    Rhit     33
2   Yashu     44
3    Raja     55
4  Gaurav     85
5  Sachin     95

In [11]:
import numpy as np

In [12]:
n1=np.array([1,2,3,4,45])

In [13]:
n1

array([ 1,  2,  3,  4, 45])

In [19]:
n2=np.array([[1,2,3],[4,5,6]])

In [20]:
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
n1=np.zeros((2,2))

In [25]:
n1

array([[0., 0.],
       [0., 0.]])

In [28]:
n1=np.full([2,2],15)

In [29]:
n1

array([[15, 15],
       [15, 15]])

In [32]:
n1=np.random.randint(1,100,5)

In [33]:
n1

array([53, 54, 18, 77, 58])

In [34]:
n1=np.arange(10,20)

In [35]:
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
n1=np.arange(10,1000,20)

In [37]:
n1

array([ 10,  30,  50,  70,  90, 110, 130, 150, 170, 190, 210, 230, 250,
       270, 290, 310, 330, 350, 370, 390, 410, 430, 450, 470, 490, 510,
       530, 550, 570, 590, 610, 630, 650, 670, 690, 710, 730, 750, 770,
       790, 810, 830, 850, 870, 890, 910, 930, 950, 970, 990])

In [38]:
n1=np.array([[1,2,3],[4,5,6]])

In [39]:
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
n1.shape

(2, 3)

In [42]:
n1.shape=(3,2)

In [43]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
n1=np.array([1,2,3,4,45,6])
n2=np.array([11,44,55,22,33,5])

In [52]:
np.vstack((n1,n2))

array([[ 1,  2,  3,  4, 45,  6],
       [11, 44, 55, 22, 33,  5]])

In [55]:
np.vstack((n1,n2))

array([[ 1,  2,  3,  4, 45,  6],
       [11, 44, 55, 22, 33,  5]])

In [56]:
np.vstack((n1,n2))

array([[ 1,  2,  3,  4, 45,  6],
       [11, 44, 55, 22, 33,  5]])

In [58]:
np.vstack((n1,n2))

array([[ 1,  2,  3,  4, 45,  6],
       [11, 44, 55, 22, 33,  5]])

In [59]:
np.hstack((n1,n2))

array([ 1,  2,  3,  4, 45,  6, 11, 44, 55, 22, 33,  5])

In [60]:
np.column_stack((n1,n2))

array([[ 1, 11],
       [ 2, 44],
       [ 3, 55],
       [ 4, 22],
       [45, 33],
       [ 6,  5]])

In [62]:
np.intersect1d(n1,n2)

array([], dtype=int32)

In [63]:
np.setdiff1d(n1,n2)

array([ 1,  2,  3,  4,  6, 45])

In [71]:
n1=np.array([1,22,3,22,5])
n2=np.array([3,4,54,22,77])

In [73]:
np.setdiff1d(n1,n2)

array([1, 5])

In [74]:
n1

array([ 1, 22,  3, 22,  5])

In [75]:
n2

array([ 3,  4, 54, 22, 77])

In [86]:
np.setdiff1d(n2-n1)

TypeError: _setdiff1d_dispatcher() missing 1 required positional argument: 'ar2'

In [87]:
n1=np.array([22,455,44,66,88])
n2=np.array([5445,666,998,222,44])

In [89]:
np.setdiff1d(n2,n1)

array([ 222,  666,  998, 5445])

In [90]:
np.sum([n1,n2])

8050

In [91]:
np.sum([n1,n1],axis=0)

array([ 44, 910,  88, 132, 176])

In [92]:
np.sum([n1,n2],axis=1)

array([ 675, 7375])

In [97]:
import pandas as pd

In [1]:
s1=pd.series([1,2,3,4,5])

NameError: name 'pd' is not defined

In [105]:
iris=pd.read_csv('sample3.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'sample3.csv'